version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - PORT=5173
      - ORIGIN=http://localhost:5173
